version: "3.9"

services:
  db:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  users-service:
    build: ./users
    container_name: users-service
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: ${USERS_DATABASE_URL}
    ports:
      - "8001:8001"
    networks:
      - backend

  products-service:
    build: ./products
    container_name: products-service
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: ${PRODUCTS_DATABASE_URL}
    ports:
      - "8002:8002"
    networks:
      - backend

  orders-service:
    build: ./orders
    container_name: orders-service
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: ${ORDERS_DATABASE_URL}
    ports:
      - "8003:8003"
    networks:
      - backend

  gateway-service:
    build: ./gateway
    container_name: gateway-service
    environment:
      - USERS_URL=http://localhost:8001
      - PRODUCTS_URL=http://localhost:8002
      - ORDERS_URL=http://localhost:8003
    restart: always
    depends_on:
      - users-service
      - products-service
      - orders-service
    ports:
      - "8000:8000"
    networks:
      - backend

volumes: 
  pgdata:

networks:
  backend:
